name: PHPStan

on: [push, pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Create Vendor Directory
        run: |
          echo Making directory...
          mkdir vendor
          echo Directory made.
      - name: wget virions, customui
        uses: wei/wget@v1
        with:
          args: -O vendor/customui.phar https://poggit.pmmp.io/r/44509/customui_dev-31.phar
      - name: wget virions, Commando
        uses: wei/wget@v1
        with:
          args: -O vendor/Commando.phar https://poggit.pmmp.io/r/67875/Commando_dev-27.phar
      - name: wget virions, libasynql
        uses: wei/wget@v1
        with:
          args: -O vendor/libasynql.phar https://poggit.pmmp.io/r/42454/libasynql_dev-99.phar
      - name: Run PHPStan
        uses: nxtlvlsoftware/pmmp-phpstan-action@3
        with:
          phpstan-config: phpstan.neon.dist
